# Problema de diagnostico de diabetes
<font size="4">
Detectar posibles personas con diabetes.</font>

In [2]:
import numpy as np
import pandas as pd
import math
from sklearn.model_selection import train_test_split

In [4]:
# Leer el archivo CSV
df = pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
#X_in = df.drop('Outcome', axis=1)  # Todas las columnas excepto 'Outcome'
y_in = df['Outcome']  # Solo la columna 'Outcome'
# Convertir a arreglos de NumPy

# Seleccionar las columnas deseadas
X_in = df[['Glucose', 'Age', 'BloodPressure', 'Insulin']]

# Dividir los datos en conjuntos de entrenamiento y prueba
x_train, x_test, y_train, y_test = train_test_split(X_in, y_in, test_size=0.2, random_state=42)

x_init = x_train.to_numpy()
y_init = y_train.to_numpy()

# Verificar los tamaños de los conjuntos
print("Tamaño de x_train:", x_train.shape)
print("Tamaño de x_test:", x_test.shape)
print("Tamaño de y_train:", y_train.shape)
print("Tamaño de y_test:", y_test.shape)
print("Tamaño de x_init:", x_init.shape)
print("Tamaño de y_init:", y_init.shape)

Tamaño de x_train: (614, 4)
Tamaño de x_test: (154, 4)
Tamaño de y_train: (614,)
Tamaño de y_test: (154,)
Tamaño de x_init: (614, 4)
Tamaño de y_init: (614,)


In [6]:
m,n=x_init.shape
print(m)
print(n)
print(x_init)
print(y_init)

614
4
[[ 84  21   0   0]
 [112  50  82   0]
 [139  22  46  83]
 ...
 [101  38  86   0]
 [141  29   0   0]
 [125  21  96   0]]
[0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 1 0 1
 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 1 1
 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 1 1 0 0 1 1 0 0 0 0 1 0 1 0 0 1 1 0 0 1
 1 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 1 1 0
 0 1 0 0 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 1 1 1 0
 0 0 0 0 1 1 1 1 0 0 1 0 0 1 1 0 1 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 1 0 0
 1 0 1 0 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 0 0 0 1 1 1
 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 1 1 1 1 1 0 0 0 0 0 1 1 0 1 1
 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 1 0 1 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0
 0 0 1 0 0 1 0 1 0 1 1 0 0 0 0 0 1 1 1 1 0 0 0 1 

In [7]:
def calc_costo(x, y, w, b):
    m, n = x.shape
    
    costo=0
    for i in range (m):
        z=np.dot(w,x[i])+b
        g=1/(1+np.exp(-z))
        m = len(y)  # Número de elementos en y
        #costo = costo - (1/m) * np.sum(y[i] * np.log(g) + (1 - y[i]) * np.log(1 - g))
        costo = costo - (y[i] * np.log(g) + (1 - y[i]) * np.log(1 - g))
    total_cost=costo*(1/m) 
      
    return total_cost

In [8]:
m, n = x_init.shape

# Compute and display cost with w and b initialized to zeros
initial_w = np.zeros(n)
initial_b = 0.
cost = calc_costo(x_init, y_init, initial_w, initial_b)
print('Cost at initial w and b (zeros): {:.3f}'.format(cost))

Cost at initial w and b (zeros): 0.693


In [9]:
def calc_descenso_gradiente(x,y,w,b,alpha,iter):
    m,n = x.shape 
    for k in range(iter):
        J=calc_costo(x,y,w,b)
        if k% math.ceil(iter / 10) == 0:
            print("Iteracion: {}  Costo : {} ".format(k, J))
        if(J<0.01):
            break
        deriv_w=np.zeros((n,))
        deriv_b=0.0
        for i in range(m):
            fwb=np.dot(x[i],w)+b
            g=1/(1+np.exp(-fwb))
            y_approx=(g-y[i])
            for j in range(n):
                deriv_w[j]= deriv_w[j] + y_approx*x[i,j]
            deriv_b = deriv_b + y_approx
        w= w - alpha * deriv_w/m
        b= b - alpha * deriv_b/m
    return w,b
    

In [11]:
w_init=-0.1 * (np.random.rand(n) - 0.5)
b_init=0.8
w_fin,b_fin=calc_descenso_gradiente(x_init, y_init, w_init, b_init,0.0001,1000 )

Iteracion: 0  Costo : 2.251029129344171 
Iteracion: 100  Costo : 0.694273208836388 
Iteracion: 200  Costo : 0.663237980452765 
Iteracion: 300  Costo : 0.6579182343299718 
Iteracion: 400  Costo : 0.6567899947637345 
Iteracion: 500  Costo : 0.6565150513700998 
Iteracion: 600  Costo : 0.6564334283414732 
Iteracion: 700  Costo : 0.6563979504509442 
Iteracion: 800  Costo : 0.6563738290268053 
Iteracion: 900  Costo : 0.656352582868145 


In [12]:
w_fin

array([ 0.00876947,  0.01044351, -0.03867747,  0.00043221])

In [13]:
b_fin

np.float64(0.795135329800581)

In [49]:
x_init=x_train
y_init=y_train
m, n = x_init.shape
w_init = np.zeros(n)
b_init = 0.

In [79]:
x_init = x_train[['Glucose', 'Age', 'BloodPressure', 'Insulin']]
# Convertir a arreglos de NumPy (opcional)
X = x_init.to_numpy()
y= y_train.to_numpy()
print(X.shape)
print(y.shape)

(614, 4)
(614,)


In [11]:
print(X)
print(y)

NameError: name 'X' is not defined

In [9]:
#x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)