# Problema de diagnostico de diabetes
<font size="4">
Detectar posibles personas con diabetes.</font>

In [1]:
import numpy as np
import pandas as pd
import math
from sklearn.model_selection import train_test_split

In [2]:
# Leer el archivo CSV
df = pd.read_csv('phishing.csv')
df.head()

Index  UsingIP  LongURL  ShortURL  Symbol@  Redirecting//  PrefixSuffix-  \
0      0        1        1         1        1              1             -1   
1      1        1        0         1        1              1             -1   
2      2        1        0         1        1              1             -1   
3      3        1        0        -1        1              1             -1   
4      4       -1        0        -1        1             -1             -1   

   SubDomains  HTTPS  DomainRegLen  ...  UsingPopupWindow  IframeRedirection  \
0           0      1            -1  ...                 1                  1   
1          -1     -1            -1  ...                 1                  1   
2          -1     -1             1  ...                 1                  1   
3           1      1            -1  ...                -1                  1   
4           1      1            -1  ...                 1                  1   

   AgeofDomain  DNSRecording  WebsiteTraffic  PageRank  GoogleIndex  \
0           -1            -1               0        -1            1   
1            1            -1               1        -1            1   
2           -1            -1               1        -1            1   
3           -1            -1               0        -1            1   
4            1             1               1        -1            1   

   LinksPointingToPage  StatsReport  class  
0                    1            1     -1  
1                    0           -1     -1  
2                   -1            1     -1  
3                    1            1      1  
4                   -1           -1      1  

[5 rows x 32 columns]

In [4]:
#X_in = df.drop('Outcome', axis=1)  # Todas las columnas excepto 'Outcome'
y_in = df['class']  # Solo la columna 'Outcome'
# Convertir a arreglos de NumPy

# Seleccionar las columnas deseadas
X_in = df[['Index', 'UsingIP', 'LongURL', 'Symbol@']]

# Dividir los datos en conjuntos de entrenamiento y prueba
x_train, x_test, y_train, y_test = train_test_split(X_in, y_in, test_size=0.2, random_state=42)

x_init = x_train.to_numpy()
y_init = y_train.to_numpy()

# Verificar los tamaños de los conjuntos
print("Tamaño de x_train:", x_train.shape)
print("Tamaño de x_test:", x_test.shape)
print("Tamaño de y_train:", y_train.shape)
print("Tamaño de y_test:", y_test.shape)
print("Tamaño de x_init:", x_init.shape)
print("Tamaño de y_init:", y_init.shape)

Tamaño de x_train: (8843, 4)
Tamaño de x_test: (2211, 4)
Tamaño de y_train: (8843,)
Tamaño de y_test: (2211,)
Tamaño de x_init: (8843, 4)
Tamaño de y_init: (8843,)


In [5]:
m,n=x_init.shape
print(m)
print(n)
print(x_init)
print(y_init)

8843
4
[[  480     1     1     1]
 [10811    -1    -1     1]
 [ 4064     1     1     1]
 ...
 [ 5390     1    -1    -1]
 [  860     1    -1     1]
 [ 7270     1    -1     1]]
[-1 -1  1 ...  1  1 -1]


In [6]:
def calc_costo(x, y, w, b):
    m, n = x.shape
    
    costo=0
    for i in range (m):
        z=np.dot(w,x[i])+b
        g=1/(1+np.exp(-z))
        m = len(y)  # Número de elementos en y
        #costo = costo - (1/m) * np.sum(y[i] * np.log(g) + (1 - y[i]) * np.log(1 - g))
        costo = costo - (y[i] * np.log(g) + (1 - y[i]) * np.log(1 - g))
    total_cost=costo*(1/m) 
      
    return total_cost

In [7]:
m, n = x_init.shape

# Compute and display cost with w and b initialized to zeros
initial_w = np.zeros(n)
initial_b = 0.
cost = calc_costo(x_init, y_init, initial_w, initial_b)
print('Cost at initial w and b (zeros): {:.3f}'.format(cost))

Cost at initial w and b (zeros): 0.693


In [8]:
def calc_descenso_gradiente(x,y,w,b,alpha,iter):
    m,n = x.shape 
    for k in range(iter):
        J=calc_costo(x,y,w,b)
        if k% math.ceil(iter / 10) == 0:
            print("Iteracion: {}  Costo : {} ".format(k, J))
        if(J<0.01):
            break
        deriv_w=np.zeros((n,))
        deriv_b=0.0
        for i in range(m):
            fwb=np.dot(x[i],w)+b
            g=1/(1+np.exp(-fwb))
            y_approx=(g-y[i])
            for j in range(n):
                deriv_w[j]= deriv_w[j] + y_approx*x[i,j]
            deriv_b = deriv_b + y_approx
        w= w - alpha * deriv_w/m
        b= b - alpha * deriv_b/m
    return w,b
    

In [22]:
w_init=-0.1 * (np.random.rand(n) - 0.5)
b_init=0.8
w_fin,b_fin=calc_descenso_gradiente(x_init, y_init, w_init, b_init,0.001,10 )

C:\Users\HUAWEI\AppData\Local\Temp\ipykernel_26660\1648651501.py:10: RuntimeWarning: divide by zero encountered in log
  costo = costo - (y[i] * np.log(g) + (1 - y[i]) * np.log(1 - g))
C:\Users\HUAWEI\AppData\Local\Temp\ipykernel_26660\1648651501.py:10: RuntimeWarning: invalid value encountered in scalar multiply
  costo = costo - (y[i] * np.log(g) + (1 - y[i]) * np.log(1 - g))


Iteracion: 0  Costo : nan 


C:\Users\HUAWEI\AppData\Local\Temp\ipykernel_26660\1648651501.py:7: RuntimeWarning: overflow encountered in exp
  g=1/(1+np.exp(-z))
C:\Users\HUAWEI\AppData\Local\Temp\ipykernel_26660\1648651501.py:10: RuntimeWarning: invalid value encountered in scalar subtract
  costo = costo - (y[i] * np.log(g) + (1 - y[i]) * np.log(1 - g))
C:\Users\HUAWEI\AppData\Local\Temp\ipykernel_26660\3345793190.py:13: RuntimeWarning: overflow encountered in exp
  g=1/(1+np.exp(-fwb))


Iteracion: 1  Costo : nan 
Iteracion: 2  Costo : nan 
Iteracion: 3  Costo : nan 
Iteracion: 4  Costo : nan 
Iteracion: 5  Costo : nan 
Iteracion: 6  Costo : nan 
Iteracion: 7  Costo : nan 
Iteracion: 8  Costo : nan 
Iteracion: 9  Costo : nan 


In [20]:
w_fin

array([4.53816562e+01, 7.54899022e-02, 1.65974092e-02, 9.40682419e-03])

In [21]:
b_fin

np.float64(0.8117363112008438)

In [49]:
x_init=x_train
y_init=y_train
m, n = x_init.shape
w_init = np.zeros(n)
b_init = 0.

In [79]:
x_init = x_train[['Glucose', 'Age', 'BloodPressure', 'Insulin']]
# Convertir a arreglos de NumPy (opcional)
X = x_init.to_numpy()
y= y_train.to_numpy()
print(X.shape)
print(y.shape)

(614, 4)
(614,)


In [11]:
print(X)
print(y)

NameError: name 'X' is not defined

In [9]:
#x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)